aws-load-balancer-controller:
  serviceAccount:
    create: true
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::250832144271:role/load-balancer-controller
    name: aws-loadbalancer-controller
  
  clusterName: SnapVibe-cluster
  region: ap-northeast-2