apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snapvibe-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
   - http:
      paths:
        - path: /argocd
          backend:
            serviceName: argocd-server
            servicePort: 80