istioOperator:
  profile: default
  service:
    externalTrafficPolicy: Local
  hpaSpec:
    minReplicas: 2
    maxReplicas: 10
  serviceType: LoadBalancer 
  servicePorts:
    - name: http
      port: 80
      targetPort: 8080
    - name: helath
      port: 15020
      targetPort: 15020
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-name: istio-ingress-nlb
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

hub: gcr.io/istio-testing
tag: latest

imagePullSecrets: []
imagePullPolicy: ""
watchedNamespaces: istio-system
waitForResourcesTimeout: 300s
enableCRDTemplates: false
revision: ""
deploymentHistory: 0