projects:
  - name: snapvibe-application
    applications:
      - name: snapvibe-services
        namespace: argocd
        source:
          path: app-of-apps
          repoURL: https://github.com/Masasak/v1-gitops-manifest.git
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
  - name: snapvibe-resources
    applications:
      - name: istio-resource
        namespace: argocd
        source:
          path: apps/istio-resource
          repoURL: https://github.com/Masasak/v1-kube-resource.git
        syncPolicy:
          automated:
            prune: false
            selfHeal: true