projects:
  - name: snapvibe-application
    applications:
      - name: snapvibe-services
        namespace: argocd
        source:
          path: app-of-apps
          repoURL: https://github.com/Masasak/v1-gitops-manifest.git
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
      - name: snapvibe-ingress
        namespace: argocd
        source:
          path: apps/ingress
          repoURL: https://github.com/Masasak/v1-kube-resource.git
        syncPolicy:
          automated:
            prune: true
            selfHeal: true