projects:
  - name: snapvibe-application
    applications:
      - name: snapvibe-services
        namespace: argocd
        source:
          path: apps
          repoURL: https://github.com/Masasak/v1-gitops-manifest.git
        syncPolicy:
          automated:
            prune: true
            selfHeal: true