apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  components:
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        {{- with .Values.nodeSelector }}
        nodeSelector: {{ toYaml . | nindent 10 }}
        {{- end }}
    ingressGateways:
    - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          istio: istio-ingressgateway
          service.istio.io/canonical-name: istio-ingressgateway
        k8s:
          hpaSpec:
            minReplicas: 2
          {{- with .Values.nodeSelector }}
          nodeSelector: {{ toYaml . | nindent 12 }}
          {{- end }}
          service:
            type: LoadBalancer
            ports:
            {{- range .Values.istioOperator.servicePorts }}
            - name: {{ .name }}
              port: {{ .port }}
              targetPort: {{ .targetPort }}
            {{- end }}
            externalTrafficPolicy: {{ .Values.istioOperator.service.externalTrafficPolicy }}
          {{- with .Values.istioOperator.serviceAnnotations }}
          serviceAnnotations: {{ toYaml . | nindent 12 }}
          {{- end }}
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
  meshConfig:
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
