name: Helm Chart Publish
on:
    push:
        branches: [ "main" ]
        paths: [ "helm-charts/**" ]

permissions: read-all

jobs:
    chart-publish:
        permissions:
            contents: write
            packages: write
            pages: write
            deployments: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
              with:
                fetch-depth: 0
            
            - name: Install Helm
              uses: azure/setup-helm@v3.5
              with:
                version: v3.10.1
            
            - name: Add Public Helm repos
              run: |
                helm repo add argo https://argoproj.github.io/argo-helm
                helm repo add eks https://aws.github.io/eks-charts
            
            - name: Helm build
              run: |
                changed_helm_packages=$(git diff --name-only HEAD~1 | grep '^helm-charts/' | cut -d/ -f1-2)

                while IFS=$'\n' read -r package_directory; do
                helm dependency build $package_directory
                helm package $package_directory
                done <<< "$changed_helm_packages"
            
            - name: checkout gh-pages branch and helm index
              run: | 
                git checkout helm-repository --
                helm repo index .
            
            - name: Commit The Chart Realease
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: ${{ github.event.head_commit.message }}
                commit_options: '--no-verify --signoff'
                branch: helm-repository
                skip_checkout: true
                repository: .
                commit_user_name: Masasak-Admin
                commit_user_email: team.Masasak@gmail.com
                commit_author: Masasak-Admin <team.Masasak@gmail.com>